# Nombre de la app
spring.application.name=goBooks
# Puerto de la app
server.port:8084
# Url jdbc de conexion a bbdd
spring.datasource.url=jdbc:mysql://localhost:3306/books
# Usuario y password de la bbdd
spring.datasource.username=root
spring.datasource.password=formacion
# Driver de mysql para la comunicacion jdbc
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Ubicacion y puerto del servidor Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Configuracion del almacenamiento de sesiones en redis
spring.session.store-type=redis
# Evita que Spring intente configurar Redis automaticamente
spring.session.redis.configure-action=none
# Vlcado inmediato de datos a Redis tras cambios
spring.session.redis.flush-mode=immediate
# Prefijo de nombre para las claves dentro de Redis
spring.session.redis.namespace=myapp:session
# Permiso de dependencias circulares entre beans
spring.main.allow-circular-references=true
# Nivel de detalle del log para los paquetes del proyecto
logging.level.com.atrium.gobooks=debug


